### ISSUE TITLE
blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://render.githubusercontent.com' that is not equal to the supplied origin.

### ISSUE THREAD

**Issue by MuthuChess** [octokit/core.js#158]
Hi Team,

I'm trying to access github api via browser from my react web based application. I Installed npm octokit/core.

I followed this procedure https://docs.github.com/en/rest/reference/repos#download-a-repository-archive to download the zip artifact from a public repository.

The image shows the request headers which has origin null.
![image](https://user-images.githubusercontent.com/35551343/89651563-c2765e80-d8e1-11ea-936b-e9e35468303b.png)

**Error:** Access to fetch at 'https://codeload.github.com/{owner}/{repo}/legacy.zip/master' (redirected from 'https://api.github.com/repos/{owner}/{repo}/zipball/master') from origin 'http://localhost:3001' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://render.githubusercontent.com' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Please let me know if you require any details

Regards,
Muthu.

**Comment by gr2m** [comment]
We are aware of the problem, there is unfortunately nothing we can do about it.

If think your issue is the same as https://github.com/octokit/rest.js/issues/758, would you mind watching that one? I'll comment there as soon as there are any changes about CORS settings.

I'm also maintaining https://github.com/gr2m/github-api-wishlist/tree/master/wishlist/cors-for-adjacent-domains as an effort to provide the best context information possible to the engineers working on the GitHub API

**Comment by vasilvestre** [comment]
There's still no way to download a tarball or release content from octokit ?

**Comment by gr2m** [comment]
Unfortunately, no.

**Comment by sekedus** [comment]
Related: community/community#106849
