### ISSUE TITLE
Regarding Check Run ID in API

### ISSUE THREAD

**Issue by Hardik0307** [octokit/core.js#215]
Hello,

Is there any JSON in pulls that gives **check-run-id** or **check-suite-id** ?

Basically, I need checks status for a particular PR.

I read [PR doc](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls) but couldn't find it.

Thanks in advance :pray:

**Comment by gr2m** [comment]
A better place to ask general questions about GitHub's APIs is [GitHub's GitHub API Development and Support forum](https://github.community/c/github-api-development-and-support/37)

Check runs / suits are not directly attached to pull requests, but to commits. So you'll want to find the `head` commit of the pull request in question and then load the check runs, then you can

1. [List check runs for a git reference](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#list-check-runs-for-a-git-reference)
2. [List check suits for a git reference](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#list-check-suites-for-a-git-reference)

Instead of using the REST API calls, you can also send a GraphQL query which might be more efficient, depending on your use case

**Comment by Hardik0307** [comment]
Now onwards will ask on the forum.
@gr2m it was really helpful.

**Comment by gr2m** [comment]
Happy to help :)
