### ISSUE TITLE
Availability as a local package

### ISSUE THREAD

**Issue by thdoan** [octokit/core.js#318]
**What’s missing?**

It would be awesome if core.js can be downloaded and used as a local JS file.

**Why?**

Chrome extensions Manifest V3 (MV3) has a new security restriction prohibiting linking to external scripts. Fortunately MV3 is still in a preview state, but when it's finally enforced we should be prepared for it. This is causing a headache for many extension developers who rely on third-party libraries, including Google's own [GAPI](https://github.com/google/google-api-javascript-client/issues/713).

More info here: https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#remotely-hosted-code

**Comment by wolfy1339** [comment]
This can be done by adding [`@pika/plugin-bundle-web`](https://github.com/snowpackjs/pika-pack-builders/tree/master/packages/plugin-bundle-web) to the build steps

**Comment by gr2m** [comment]
I used to upload bundled builds to releases, but it added to the overhead. I'd prefer to remove build steps from @octokit, not add to it. Ideally there would be a service that could bundle up a module on demand, so that bugs caused by the bundling itself would be fixed for past versions, too.

For now, you'll have to do the bundling yourself, sorry.

**Comment by thdoan** [comment]
Thanks, adding `@pika/plugin-bundle-web` to the build works for me.
